services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: readypi
    ports:
      - "5432:5432"
    volumes:
      - readypi_db_data:/var/lib/postgresql/data

volumes:
  readypi_db_data:
